setwd("~/Work/Metagenomic_Analysis/Final_Analysis/GenomeReconstuction/Bins_distribution")
bins_distribution <- read.csv (file="Bins_depth_distribute.txt", sep="\t", row.names=1, header=T)
bins_distribution_t <- data.frame(t(bins_distribution))
bin_proportions <- bins_distribution_t/colSums(bins_distribution_t)[col(bins_distribution_t)]*100
bin_distribution_proportions <- data.frame(t(bin_proportions))
row.names (bin_distribution_proportions)
meta <- read.csv (file = "../../Metadata.txt", sep="\t", row.names=1, header=T)
row.names (meta)

kruskalmc (bin_distribution_proportions$Bin126 ~ meta$Group1)
kruskalmc (bin_distribution_proportions$Bin148 ~ meta$Group1)
kruskalmc (bin_distribution_proportions$Bin217 ~ meta$Group1)
kruskalmc (bin_distribution_proportions$Bin245 ~ meta$Group1)
kruskalmc (bin_distribution_proportions$Bin372 ~ meta$Group1)
kruskalmc (bin_distribution_proportions$Bin487 ~ meta$Group1)
kruskalmc (bin_distribution_proportions$Bin633 ~ meta$Group1)
kruskalmc (bin_distribution_proportions$Bin727 ~ meta$Group1)

boxplot (sqrt(bin_distribution_proportions$Bin126) ~ meta$Group1)
boxplot (sqrt(bin_distribution_proportions$Bin148) ~ meta$Group1)
boxplot (sqrt(bin_distribution_proportions$Bin217) ~ meta$Group1)
boxplot (sqrt(bin_distribution_proportions$Bin245) ~ meta$Group1)
boxplot (sqrt(bin_distribution_proportions$Bin372) ~ meta$Group1)
boxplot (sqrt(sqrt(bin_distribution_proportions$Bin487)) ~ meta$Group1)
boxplot (sqrt(bin_distribution_proportions$Bin633) ~ meta$Group1)
boxplot (sqrt(bin_distribution_proportions$Bin727) ~ meta$Group1)

jpeg("Bin148_new.jpg", height = 3, width = 2, units = 'in', res = 600)
boxplot(bin_distribution_proportions$Bin148 ~ meta$Group1, col=c("brown4", "orangered3", "green4", "limegreen"), ylab="Relative depth of Bin148", cex.axis=0.8, par(cex.lab=0.8), par(cex.axis=0.8), ylim = c(0, 15))
stripchart(bin_distribution_proportions$Bin148 ~ meta$Group1, vertical = TRUE, method = "jitter", add = TRUE, pch = 20, col = 'black')
dev.off ()
jpeg("Bin126.jpg", height = 4, width = 3, units = 'in', res = 600)
boxplot(sqrt(bin_distribution_proportions$Bin126) ~ meta$Group1, col=c("brown4", "orangered3", "green4", "limegreen"), ylab="sqrt (Relative depth of Bin26)", cex.axis=0.8, par(cex.lab=0.8), par(cex.axis=0.8))
stripchart(sqrt(bin_distribution_proportions$Bin126) ~ meta$Group1, vertical = TRUE, method = "jitter", add = TRUE, pch = 20, col = 'black')
dev.off ()
jpeg("Bin487_new2.jpg", height = 3, width = 2, units = 'in', res = 600)
boxplot(bin_distribution_proportions$Bin487 ~ meta$Group1, col=c("brown4", "orangered3", "green4", "limegreen"), ylab="Relative depth of Bin487", cex.axis=0.8, par(cex.lab=0.8), par(cex.axis=0.8), ylim = c(0, 17))
stripchart(bin_distribution_proportions$Bin487 ~ meta$Group1, vertical = TRUE, method = "jitter", add = TRUE, pch = 20, col = 'black')
dev.off ()

#-------- Final Distribution Graph which was Used
bin_distribution_proportions_meta <- cbind (bin_distribution_proportions, meta)
write.table(bin_distribution_proportions_meta, file="bin_distribution_proportions_meta.txt", sep="\t")

bin_distribution_proportions_meta <- read.csv(file="bin_distribution_proportions_meta.txt",sep="\t",row.names=1,header=T)
jpeg("Bin148_distribution_New.jpg", height = 5, width = 7, units = 'in', res = 600)
barplot(bin_distribution_proportions_meta$Bin148, col=c("brown4", "orangered3", "green4", "limegreen")[bin_distribution_proportions_meta$Group1])
dev.off ()
jpeg("Bin487_distribution_New.jpg", height = 5, width = 7, units = 'in', res = 600)
barplot(bin_distribution_proportions_meta$Bin487, col=c("brown4", "orangered3", "green4", "limegreen")[bin_distribution_proportions_meta$Group1])
dev.off ()

#---- Pvalues for Gorilla and Human
bin_distribution_human <- subset(bin_distribution_proportions_meta, Group=="Human")
wilcox.test(bin_distribution_human$Bin148 ~ bin_distribution_human$Group1)
wilcox.test(bin_distribution_human$Bin487 ~ bin_distribution_human$Group1)

bin_distribution_gorilla <- subset(bin_distribution_proportions_meta, Group=="Gorilla")
wilcox.test(bin_distribution_gorilla$Bin148 ~ bin_distribution_gorilla$Group1)
wilcox.test(bin_distribution_gorilla$Bin487 ~ bin_distribution_gorilla$Group1)
